# Production configuration

server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read:user
              - user:email

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${ISSUER}

    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:900}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:604800}

    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}

    cookie-secure: true
    cookie-http-only: true
    cookie-same-site: none
    cookie-domain:

app:
  cors:
    front-end-url: ${FRONTEND_URL}

  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_URL}
      failure-redirect: ${FRONT_END_FAILURE_URL}